version: '3.8'

services:
  windows10:
    image: dockurr/windows
    container_name: win10_codespace
    environment:
      VERSION: "10"
      # Ajustado para consumir os 32GB de RAM e 200GB de disco solicitados
      RAM_SIZE: "32G"
      DISK_SIZE: "210G"
      # Habilita o suporte a drivers virtuais de alta performance (VirtIO)
      ALLOCATE: "Y"
    devices:
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    # Mapeamento de recursos para habilitar a GPU RTX 3060 dentro do Windows Containerizado
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8009:8006" # Interface Web (VNC)
      - "3389:3389" # Porta nativa do RDP (Conexão de Área de Trabalho Remota do Windows)
    volumes:
      - win_data:/storage
    restart: always

volumes:
  win_data:
